name: On PR

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: tsc
        run: npm run tsc
